{% set name = "sqcircuit" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dbfe1728fbd32553a9d4627f4c29e843df4cd83d3db452e0a42a93919da42392

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - dill >=0.3.4
    - matplotlib-base >=3.0.0
    - numpy >=1.14.2
    - python >={{ python_min }}
    - qutip >=5.0.0
    - scipy >=1.1.0
    - IPython >=7.0.0
    - pytorch >=2.0
    - mpmath >=1.2.1
    - sympy >=1.13.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - SQcircuit

about:
  home: https://sqcircuit.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: superconducting quantum circuit analyzer
  doc_url: https://docs.sqcircuit.org/
  dev_url: https://github.com/stanfordLINQS/SQcircuit

extra:
  recipe-maintainers:
    - taha1373
